# Generated by Django 4.1.3 on 2022-11-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_album_comment_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
