# Generated by Django 4.1.3 on 2022-11-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_alter_album_id_alter_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_img',
        ),
    ]
