# Generated by Django 4.1.3 on 2022-11-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_remove_song_song_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='year',
        ),
    ]
